### ISSUE TITLE
Enhanced Instance Creation with ONTAP NFS as a Cinder Backend in NetApp OpenStack Docs

### ISSUE THREAD

**Issue by gnarl** [NetApp-openstack-dev/openstack-docs#3]
- [x ] This doc is inaccurate in this way: Step 8 in Table 5.1 is actually Step 7 in the step instructions.

-----------------------------------
Release: 2017.2 on 2017-09-14 18:13
SHA: 272402c004695e8d24e872085c9278d7182c7cc2
Source: https://github.com/NetApp-openstack-dev/openstack-docs/glance/configuration/section_glance-enhanced-instance-config-NFS.rst
Current URL: https://netapp-openstack-dev.github.io/openstack-docs/pike/glance/configuration/section_glance-enhanced-instance-config-NFS.html
Filed against: PIKE

**Comment by mchad1** [comment]
Thank you for pointing this out, I am working on addressing this issue.

**Comment by mchad1** [comment]
Thank you for pointing this out, The issue is addressed.

**Comment by gouthampacha** [comment]
This issue was fixed

commit 69686e19e8e2c9f6a5273e84c42b0c0014d48d19 on master
commit 43a53f507eacaaa2ad36ab9bdb304adae3a21472 on stable/pike
commit c13ede38ef9f3cf7ee8db868d98c3e97bc468a53 on stable/ocata
